Controllers films users
NurievLinar/java-filmorate pull request #1
Opened 2023-01-25 10:50 UTC by NurievLinar

2023-01-25 20:41 UTC, sergeymamonov requested changes
Ошибки часто возникают от невалидных данных. Поэтому тесты с невалидными данными помогают избежать многих ошибок.

2023-01-25 20:41 UTC, sergeymamonov commented on .gitignore
> -*.class
Зачем изменен этот файл по сравнению с шаблоном? Так как удалены файлы с этими расширениями, то, например, файлы логов, джарники могут попасть в репозиторий. Нужно вернуть обратно, как было.

2023-01-25 20:41 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        id++;
Можно сразу return id++;

И приватные методы лучше опустить ниже в классе, а вначале расположить публичные.

2023-01-25 20:41 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))){
Дату лучше вынести в константу.

И валидацию лучше вынести в отдельный метод.

2023-01-25 20:41 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (!films.containsKey(film.getId())) {
Валидацию лучше вынести в отдельный метод.

2023-01-25 20:41 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    //private final List<User> users = new ArrayList<>();
В проекте не должно быть закомментированных строчек кода

2023-01-25 20:41 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Size(max = 200, message = "Максимальная длина описания 200 символов")
Число лучше вынести в константу.

2023-01-28 13:42 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        id++;
Не могу понять почему, если сделать так: "Можно сразу return id++;", то тесты связанные с id не проходят в Postman.

2023-01-28 13:51 UTC, NurievLinar commented on .gitignore
> -*.class
Сперва не понимал как правильно склонировать и создать репозиторий. пытался залить готовый проект раз 5. Удалял, заново склонировал, вставлял файлы из готового проекта, не получалось, удалял заново склонировал. Видимо поэтому файл подменился. Правильно будет заменить файл в моём репозитории файлом из шаблона?

2023-01-28 20:16 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))){
Сделано.

2023-01-28 20:16 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (!films.containsKey(film.getId())) {
Сделано.

2023-01-28 20:16 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    //private final List<User> users = new ArrayList<>();
Исправлено.

2023-01-28 20:16 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Size(max = 200, message = "Максимальная длина описания 200 символов")
Сделано.

2023-01-28 20:58 UTC, sergeymamonov commented on .gitignore
> -*.class
Весь файл менять не обязательно (хотя и можно). Самое простое добавить те строки, которые были удалены. Можете воспользоваться локальной историей в идея. Пара щелчков мышки и строки вернутся назад.

2023-01-28 21:03 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        id++;
Нужно смотреть, какая ошибка. Можно посмотреть в дебагере, какое поведение. Но предполагаю, что нужно изменить на return ++id; Посмотрите разницу между постфиксной и префиксной нотацией.

2023-01-28 21:11 UTC, sergeymamonov approved these changes
Нужно доработать валидацию, а именно вынести ифы и создание ошибок в методы валидации. Зачем это нужно? Чтобы в самом метод оставалось как можно меньше не связанной с основной логикой кода (а валидация это не основная логика, а вспомогательная).

2023-01-28 21:11 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @Size(max = SIZE, message = "Максимальная длина описания 200 символов")
Можно сделать еще лучше, 200 осталось в сообщении. Если изменим константу, а в сообщении забудем, то будет расхождение. Лучше использовать константу и в сообщении.

2023-01-28 21:11 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (validDate(film)){
Этот иф - это и есть валидация. Метод валидации не должен ничего возвращать. Если валидация прошла, то ок, а если не прошла, то будет кинута ошибка.

2023-01-28 21:11 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private boolean validDate (Film film) {
В метод валидации нужно перенести еще и иф, и создание ошибки.

2023-01-28 21:13 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	void addFilm () throws ValidationException {
Точно ли нужно писать throws ValidationException?

2023-02-06 10:58 UTC, merged