ФЗ 10.
NurievLinar/java-filmorate pull request #2
Opened 2023-02-12 22:09 UTC by NurievLinar

2023-02-13 12:06 UTC, sergeymamonov requested changes
Обратите внимание на сообщения для логов, они должны быть более информативными. Не пишите руками конструкторы там, где можно воспользоваться аннотациями Lombok.

2023-02-13 12:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage) {
Не обязательно писать конструктор руками. Лучше использовать аннотации Lombock.

2023-02-13 12:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new NotFoundException("Такого фильма не существует");
Лучше более полно писать, чтобы логи было легче анализировать.

NotFoundException(String.format("Фильм с id = %s не найден", id))

2023-02-13 12:09 UTC, sergeymamonov requested changes
И тесты добавьте на проверку неалидных входных значений.

2023-02-13 12:09 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new ValidationException("дата релиза — раньше 28 декабря 1895 года;");
Я бы лучше константу вставил. Чтобы эта дата была только в одном месте указана, и если нужно будет менять, то только в одном месте. А не разбросано значение по коду.

2023-02-14 11:16 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(FilmStorage filmStorage) {
Исправлено.

2023-02-14 11:16 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new NotFoundException("Такого фильма не существует");
Исправлено.

2023-02-14 11:17 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new ValidationException("дата релиза — раньше 28 декабря 1895 года;");
Константу вставил.

2023-02-14 15:17 UTC, sergeymamonov approved these changes

2023-02-14 15:17 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new ValidationException("дата релиза — раньше, чем " + DATE);
Например, в этом случае можно сделать более информативный лог, указав id фильма

2023-02-14 15:17 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public UserController(UserService userService) {
Без самописного конструктора можно обойтись, если воспользоваться аннотацией Lombok.

2023-02-14 15:17 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public FilmController(FilmService filmService) {
Аналогично, можно воспользоваться аннотацией Lombok.

2023-03-09 19:43 UTC, merged