ФЗ 11.
NurievLinar/java-filmorate pull request #3
Opened 2023-03-10 11:14 UTC by NurievLinar

2023-03-10 11:29 UTC, NurievLinar commented
Здравствуйте. перед отправкой задания, прогнал на Postman - всё работает, без ошибок.
На GitHub при проверке зависает на "Run /tmp/wait-for-it.sh -t 60 localhost:8080"

2023-03-10 12:00 UTC, NurievLinar commented
Вот ссылка на скриншот Postman.
https://disk.yandex.ru/i/8ReYwCgmlS4tMQ

2023-03-11 10:06 UTC, sergeymamonov commented
> Здравствуйте. перед отправкой задания, прогнал на Postman - всё работает, без ошибок. На GitHub при проверке зависает на "Run /tmp/wait-for-it.sh -t 60 localhost:8080"

Добрый день. Попросил вашего наставника подключиться к этому вопросу.

2023-03-11 10:06 UTC, sergeymamonov requested changes

2023-03-11 10:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        //return filmService.getById(id);
Не оставляйте в проекте закомментированного кода.

2023-03-11 10:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreController.java
> +    public GenreController(GenreService genreService) {
Не обязательно писать конструктор руками, можно пользоваться аннотацией Lombok @AllArgsConstructor. Аналогично и для других классов.

2023-03-11 10:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (id < 1000 && id > 0) {
Ограничение с 1000 непонятно. Если оно нужно, то лучше вынести 1000 в константу и дать ей информативное название.

2023-03-11 10:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (id < 9900) {
Ограничение с 9900 непонятно. Если оно нужно, то лучше вынести 9900 в константу и дать ей информативное название.

2023-03-11 10:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            if (!filmDbStorage.setGenre(film.getId(), genre.getId())) {
Не очень хорошо делать запросы к БД в цикле. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети.

2023-03-11 10:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            if (!filmDbStorage.setGenre(film.getId(), genre.getId())) {
Запросы к БД в цикле.

2023-03-11 10:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                filmDbStorage.deleteGenre(film.getId(), current.getId());
Запросы к БД в цикле.

2023-03-11 10:06 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void existsUser(Integer userId) {
Методы, которые вызываются только внутри класса, лучше делать приватными.

2023-03-12 14:24 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        //return filmService.getById(id);
Исправил.

2023-03-12 15:04 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/controllers/GenreController.java
> +    public GenreController(GenreService genreService) {
Исправил.

2023-03-12 15:12 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (id < 1000 && id > 0) {
Исправил.

2023-03-12 17:14 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (id < 9900) {
Исправил.

2023-03-12 17:21 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void existsUser(Integer userId) {
Исправлено.

2023-03-12 17:47 UTC, NurievLinar commented
Ошибка с проверкой в GitHub решилась путём изменения в data.sql `insert into` на `merge into`. Помог наставник.

2023-03-12 17:57 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            if (!filmDbStorage.setGenre(film.getId(), genre.getId())) {
Принято, спасибо. Можно в этом проекте оставлю так? Учту на будущее.

2023-03-13 13:27 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            if (!filmDbStorage.setGenre(film.getId(), genre.getId())) {
Нет, так оставлять нельзя.

2023-03-13 13:33 UTC, sergeymamonov requested changes

2023-03-13 13:33 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private static final int LIMIT = 1000;
Из названия константы непонятно, чего именно лимит.

2023-03-14 01:54 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            if (!filmDbStorage.setGenre(film.getId(), genre.getId())) {
Переделал.

2023-03-14 01:55 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            if (!filmDbStorage.setGenre(film.getId(), genre.getId())) {
Исправил.

2023-03-14 01:55 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                filmDbStorage.deleteGenre(film.getId(), current.getId());
Исправил.

2023-03-14 01:55 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private static final int LIMIT = 1000;
Исправил.

2023-03-14 20:55 UTC, sergeymamonov requested changes
Описание коммитов должно быть подробно. Не должно быть несколько коммитов с одинаковым названием. В коллективной разработке, ваши коллеги будут видеть ваши коммиты, вам может потребоваться откатиться на какой-то коммит. Если они все называются одинаково, то будет сложно понять, на какой откатываться.

Запросы к БД в цикле остались. Подсветил пару мест.

2023-03-14 20:55 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Integer> common = new HashSet<>(userDbStorage.findAllFriends(idUser));
Разве здесь findAllFriends возвращает массив с дубликатами? Предложил бы посмотреть в дебагере. Но даже если возвращает, то не самое лучше решение через множество делать. Лучше и быстрее будет работать, если сделать новый запрос, который будет как в методе findAllFriends, только с SQL словом DISTINCT. Общее правило такое, всю фильтрацию, которую можно сделать на стороне БД, лучше сделать на стороне БД. БД это сделает быстрее, так как в БД используются индексы и специальные структуры данных. И после фильтрации в БД ответ будет меньше, значит быстрее будет передан по сети.

2023-03-14 20:55 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            friends.add(getUserById(friendId));
От того, что запрос в БД обернут в метод, их не стало меньше) Запросы к БД как были в цикле, так они и остаются.

2023-03-14 20:55 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +            genres.add(new Genre(id, getById(id)));
Запросов к БД меньше не стало. Цель именно сократить запросы к БД.

2023-03-17 07:12 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +            friends.add(getUserById(friendId));
Исправлено

2023-03-17 07:12 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Integer> common = new HashSet<>(userDbStorage.findAllFriends(idUser));
Исправлено

2023-03-17 13:16 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +            genres.add(new Genre(id, getById(id)));
Исправлено

2023-03-18 06:24 UTC, sergeymamonov requested changes

2023-03-18 06:24 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setGenres(genreService.getGenresByFilmId(film.getId()));
В getGenresByFilmId выполняется запрос к БД. Значит в цикле мы делаем запросы к БД.

2023-03-18 06:24 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        for (Film film : allFilms) {
В этом цикле есть запросы к БД.

2023-03-18 07:25 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            film.setGenres(genreService.getGenresByFilmId(film.getId()));
Исправлено.

2023-03-18 08:23 UTC, NurievLinar commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        for (Film film : allFilms) {
Исправлено.

2023-03-18 08:28 UTC, NurievLinar commented
От чистого сердца Благодарю! Хорошо меня натаскали!)

2023-03-19 04:43 UTC, sergeymamonov approved these changes

2023-03-21 08:47 UTC, merged